config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'auth/result', to: 'sessions#result'
  resource 'session', only: [:new, :create, :destroy]
  post 'sessions/renew', to: 'sessions#renew'
  delete 'sessions/timeout', to: 'sessions#timeout'

  get '/', to: "dashboard#index"
  get '/dashboard', to: "dashboard#index"

  resources :evaluations, only: [:index]
  resources :evaluation_forms
  resources :manage_submissions, only: [:index]

  namespace :form_validations do
    resources :evaluation_forms, only: %i[create update]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  if Rails.env.development? || Rails.env.dev?
    get "/sandbox", to: "sandbox#index"
  end
end

app/controllers/evaluation_forms_controller.rb
# frozen_string_literal: true

class EvaluationFormsController < ApplicationController
  before_action -> { authorize_user('challenge_manager') }
  before_action :set_evaluation_form, only: %i[show edit update destroy]
  before_action :set_evaluation_forms, only: %i[index]

  # GET /evaluation_forms or /evaluation_forms.json
  def index; end

  # GET /evaluation_forms/1 or /evaluation_forms/1.json
  def show; end

  # GET /evaluation_forms/new
  def new
    @evaluation_form = EvaluationForm.new
  end

  # GET /evaluation_forms/1/edit
  def edit; end

  # POST /evaluation_forms or /evaluation_forms.json
  def create
    @evaluation_form = EvaluationForm.new(evaluation_form_params)

    respond_to do |format|
      if @evaluation_form.save
        format.html do
          redirect_to evaluation_forms_url, notice: I18n.t("evaluation_form_saved")
        end
        format.json { render :show, status: :created, location: @evaluation_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluation_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluation_forms/1 or /evaluation_forms/1.json
  def update
    respond_to do |format|
      if @evaluation_form.update(evaluation_form_params)
        format.html do
          redirect_to evaluation_forms_url, notice: I18n.t("evaluation_form_saved")
        end
        format.json { render :show, status: :ok, location: @evaluation_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluation_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_forms/1 or /evaluation_forms/1.json
  def destroy
    @evaluation_form.destroy!

    respond_to do |format|
      format.html { redirect_to evaluation_forms_url, notice: I18n.t("evaluation_form_destroyed") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_evaluation_form
    @evaluation_form = EvaluationForm.find(params[:id])
  end

  def set_evaluation_forms
    @evaluation_forms = EvaluationForm.by_user(current_user)
  end

  # Only allow a list of trusted parameters through.
  def evaluation_form_params
    permitted = params.require(:evaluation_form).
      permit(:title, :instructions, :phase_id, :status, :comments_required,
             :weighted_scoring, :publication_date, :closing_date, :challenge_id)
    closing_date = parse_closing_date(permitted[:closing_date])
    closing_date ? permitted.merge({ closing_date: }) : permitted
  end

  def parse_closing_date(input_date)
    case input_date
    when %r{\A\d\d?/\d\d?/\d\d\d\d\z} # mm/dd/yyyy, also accepts single digit month/day
      (month, day, year) = input_date.split("/")
      # nicely formatted iso8601 with 2 digit day and month
      "#{year}-#{month.rjust(2, '0')}-#{day.rjust(2, '0')}"
    else
      input_date
    end
  end
end

app/controllers/form_validations/evaluation_forms_controller.rb
class FormValidations::EvaluationFormsController < EvaluationFormsController
  def update
    @evaluation_form.assign_attributes(evaluation_form_params)
    @evaluation_form.valid?
    respond_to do |format|
      format.text do
        render partial: "evaluation_forms/form", locals: { evaluation_form: @evaluation_form }, formats: [:html]
      end
    end
  end
   
  def create
    @evaluation_form = evaluation_form.new(evaluation_form_params)
    @evaluation_form.validate
    respond_to do |format|
      format.text do
        render partial: "evaluation_forms/form", locals: { evaluation_form: @evaluation_form }, formats: [:html]
      end
    end
  end
end

app/helpers/evaluation_forms_helper.rb
# frozen_string_literal: true

module EvaluationFormsHelper
  def challenge_with_phase(evaluation_form)
    challenge_phase_title(evaluation_form.challenge, evaluation_form.phase)
  end

  def challenge_phase_title(challenge, phase)
    "#{challenge.title} - Phase #{phase_number(phase)}"
  end

  def inline_error(evaluation_form, field)
    error = evaluation_form.errors[field].present? ? evaluation_form.errors[field].first : ""
    tag.span(error, class: "text-secondary font-body-2xs", id: "evaluation_form_#{field}_error")
  end

  def eval_form_disabled?(evaluation_form)
    evaluation_form.valid? && evaluation_form.phase.end_date < Time.zone.today
  end
end

app/helpers/form_validations/evaluation_forms_helper.rb
module FormValidations::EvaluationFormsHelper
end

app/views/evaluation_forms/_evaluation_criterion_fields.html.erb
<% if f.object.persisted? %>
  <%= f.hidden_field :id, value: f.object.id %>
  <%= f.hidden_field :_destroy, class: "destroy-evaluation-criteria" %>
<% end %>

<div class="criteria-header">
  <%= f.label :title, "Criteria title", for: criteria_field_id(f, "title", is_template) %>

  <div class="display-inline">
    <%= f.text_field :title, 
      id: criteria_field_id(f, "title", is_template),
      name: criteria_field_name(f, "title", is_template),
      class: 'usa-input', 
      placeholder: 'Add criteria title here', 
      required: true, 
      disabled: is_template
    %>
  </div>
</div>

<div class="margin-top-2">
  <%= f.label :description, "Criteria description", for: criteria_field_id(f, "description", is_template) %>
  <%= f.text_area :description, 
    id: criteria_field_id(f, "description", is_template),
    name: criteria_field_name(f, "description", is_template),
    class: 'usa-textarea', 
    placeholder: 'Add criteria description here', 
    required: true, 
    disabled: is_template 
  %>
</div>

<div class="margin-top-2">
  <%= f.label :points_or_weight, "Criteria Points/Weight", for: criteria_field_id(f, "points_or_weight", is_template) %>
  <%= f.number_field :points_or_weight, 
    id: criteria_field_id(f, "points_or_weight", is_template),
    name: criteria_field_name(f, "points_or_weight", is_template),
    class: 'usa-input', 
    min: 1, 
    step: 1, 
    placeholder: "Add criteria points/weight here",
    required: true, 
    disabled: is_template 
  %>
</div>

<div class="margin-top-2">
  <%= f.label :scoring_type, "Scoring Type", for: criteria_field_id(f, "scoring_type", is_template) %>
  <% scoring_types = { "numeric" => "Numeric", "rating" => "Rating", "binary" => "Binary" } %>
  <div>
    <% scoring_types.each do |value, label| %>
      <div>
        <%= f.radio_button :scoring_type, value, 
            id: criteria_field_id(f, "scoring_type_#{value}", is_template), 
            name: criteria_field_name(f, :scoring_type, is_template),
            class: "usa-radio",
            checked: (value == "numeric"), 
            # TODO: Remove when adding other scoring_types
            disabled: (value != "numeric")  %>

        <%= label_tag criteria_field_id(f, "scoring_type_#{value}", is_template), label %>
      </div>
    <% end %>
  </div>
</div>

<div class="margin-top-2">
  <%= button_tag type: "button", class: "delete-criteria-button usa-button usa-button--unstyled", title: "Delete criteria" do %>
    Remove criteria
  <% end %>
</div>

app/views/evaluation_forms/_evaluation_form.html.erb
<div id="<%= dom_id evaluation_form %>">
  <p>
    <strong>Title:</strong>
    <%= evaluation_form.title %>
  </p>

  <p>
    <strong>Instructions:</strong>
    <%= evaluation_form.instructions %>
  </p>

  <p>
    <strong>Phase ID:</strong>
    <%= evaluation_form.phase_id %>
  </p>

  <p>
    <strong>Comments required:</strong>
    <%= evaluation_form.comments_required %>
  </p>

  <p>
    <strong>Weighted scoring:</strong>
    <%= evaluation_form.weighted_scoring %>
  </p>

  <p>
    <strong>Closing date:</strong>
    <%= evaluation_form.closing_date %>
  </p>

  <p>
    <strong>Challenge:</strong>
    <%= evaluation_form.challenge_id %>
  </p>

</div>

app/views/evaluation_forms/_form.html.erb
<%= form_with(model: evaluation_form, data: { controller: "evaluation-form" }) do |form| %>
  <%
    if evaluation_form.challenge && evaluation_form.phase
      challenge = evaluation_form.challenge
      phase = evaluation_form.phase
      combo_box_default_value = "#{challenge.id}.#{phase.id}.#{phase.end_date.strftime("%m/%d/%Y")}"
      disabled = eval_form_disabled?(evaluation_form)
    end
  %>
  <ol class="usa-process-list">
    <li class="usa-process-list__item">
      <h4 class="usa-process-list__heading">Evaluation Information</h4>
      <p class="margin-top-05">
        Create an evaluation form title, assign it to your challenge and
        provide instructions that will be shared with your evaluators. 
      </p>
      <div>
        <%= form.label :title, class: "usa-label" %>
        <%= form.text_field :title, maxlength: 150, class: "usa-input", data: {"action": "evaluation-form#validatePresence focusout->evaluation-form#validatePresence"}, disabled: disabled %>
      </div>

      <%= inline_error(evaluation_form, :title) %>

      <label class="usa-label" for="challenge-combo">Select a challenge</label>
      <div class="usa-hint">Choose the challenge this form will evaluate.</div>
      <div class="usa-combo-box" data-default-value="<%= combo_box_default_value %>">
        <select class="usa-select" <%= if disabled then "disabled" end %> id="challenge-combo" title="challenge-combo" data-action="evaluation-form#handleChallengeSelect">
          <% current_user.challenge_manager_challenges.each do |challenge| %>
            <% challenge.phases.each do |phase| %>
              <option value="<%= "#{challenge.id}.#{phase.id}.#{phase.end_date.strftime("%m/%d/%Y")}" %>"><%= challenge_phase_title(challenge, phase) %></option>
            <% end %>
          <% end %>
        </select>
      </div>
      
      <%= inline_error(evaluation_form, :challenge_id) %>
      <%= inline_error(evaluation_form, :phase_id) %>

      <%= form.hidden_field :phase_id, {data: { "evaluation-form-target": 'phaseID'}} %>
      <%= form.hidden_field :challenge_id, {data: { "evaluation-form-target": 'challengeID'}} %>

      <div class="usa-character-count">
        <div class="usa-form-group">
          <%= form.label :instructions, class: "usa-label" %>
          <%= form.text_area :instructions, class: "usa-textarea usa-character-count__field", maxlength: 3000, rows: "7", data: {"action": "evaluation-form#validatePresence focusout->evaluation-form#validatePresence"}, disabled: disabled%>
        </div>
        <span id="with-hint-textarea-info" class="usa-character-count__message">You can enter up to 3000 characters</span>
      </div>
      <%= inline_error(evaluation_form, :instructions) %>

    </li>
    <li class="usa-process-list__item">
      <h4 class="usa-process-list__heading">Evaluation Criteria</h4>
      <p>
        Build your evaluation criteria and scoring options.
      </p>
      <div class="usa-checkbox">
        <%= form.check_box :comments_required, class: "usa-checkbox__input", id: "evaluation_form_comments_required", disabled: disabled %>
        <label class="usa-checkbox__label" for="evaluation_form_comments_required">
          Require evaluators to provide comments on their scores. (optional)
          <%= image_tag 'images/usa-icons/help_outline.svg', width: 16, height: 16, alt: 'Help for comments required' %>
        </label>
      </div>

      <div>
        <fieldset class="usa-fieldset margin-top-205">
          <legend class="usa-legend usa-process-list__heading font-sans-md text-bold">
            Scale Type <span style="color: darkred;">*</span>
            <%= image_tag 'images/usa-icons/help_outline.svg', width: 16, height: 16, alt: 'Help for scale type' %>
          </legend>
          <div class="display-flex flex-row">
            <div class="usa-radio margin-right-205">
              <input class="usa-radio__input" id="point_scale" type="radio" name="evaluation_form[weighted_scoring]" value="false" <%= 'checked' unless evaluation_form.weighted_scoring %> <%= 'disabled' unless !disabled %>>
              <label class="usa-radio__label font-sans-xs" for="point_scale">Point Scale</label>
            </div>
            <div class="usa-radio">
              <input class="usa-radio__input" id="weighted_scale" type="radio" name="evaluation_form[weighted_scoring]" value="true" <%= 'checked' if evaluation_form.weighted_scoring %> <%= 'disabled' unless !disabled %>>
              <label class="usa-radio__label font-sans-xs" for="weighted_scale">Weighted Scale (%)</label>
            </div>
          </div>
        </fieldset>
      </div>
    </li>
    <li class="usa-process-list__item">
      <h4 class="usa-process-list__heading">Evaluation Period</h4>
      <p>
        Set the end date of your evaluation period.
        Your evaluation start date is the end date of your challenge.
      </p>
      <div class="usa-label">Evaluation Start Date:</div>
      <div class="usa-hint" data-evaluation-form-target="startDate">mm/dd/yyyy</div>
      <div class="usa-form-group">
        <label class="usa-label" id="evaluation_form_closing_date_label" for="evaluation_form_closing_date"
          >Evaluation End Date:</label
        >
        <div class="usa-hint" id="evaluation_form_closing_date_hint">mm/dd/yyyy</div>
        <div data-evaluation-form-target="datePicker" class="usa-date-picker" data-default-value="<%= evaluation_form.closing_date %>" data-min-date="<%= if evaluation_form.challenge then evaluation_form.challenge.end_date end %>">
          <input
            class="usa-input"
            id="evaluation_form_closing_date"
            name="evaluation_form[closing_date]"
            aria-labelledby="evaluation_form_closing_date_label"
            aria-describedby="evaluation_form_closing_date_hint"
            data-action="evaluation-form#validatePresence focusout->evaluation-form#validatePresence"
          />
        </div>
      </div>
      <%= inline_error(evaluation_form, :closing_date) %>
    </li>
  </ol>


  

  <div class="display-flex flex-wrap">
    <button type="submit" name="commit" class="mobile-lg:width-mobile usa-button font-body-2xs text-no-wrap mobile-lg:margin-left-2 mobile-lg:margin-bottom-4" style="background-color: #4d8055">
      <%= image_tag(
        "images/usa-icons/check_circle.svg",
        class: "usa-icon icon-white",
        alt: "evaluation forms"
      )%>
      Save
    </button>
    <div class="text-center width-full mobile-lg:width-auto margin-y-1 mobile-lg:margin-x-3">
      <%= link_to "Cancel", evaluation_forms_path %>
    </div>  
  </div>
<% end %>

app/views/evaluation_forms/_table.html.erb
<table class="usa-table usa-table--stacked-header usa-table--borderless width-full">
    <thead>
      <tr>
        <th scope="col">Form Title</th>
        <th scope="col">Assigned to Challenge:</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @evaluation_forms.each do |evaluation_form| %>
        <tr>
          <th data-label="Form Title" scope="row">
            <%= link_to edit_evaluation_form_path(evaluation_form) do %>
                <%= evaluation_form.title %>
            <% end %>    
            </th>
            <td data-label="Assigned to Challenge:">
                <% if evaluation_form.challenge %>
                  <%= challenge_with_phase(evaluation_form) %>
                <% end %>  
            </td>
          <td>
              <div class="display-flex flex-wrap grid-row grid-gap-1">
                <%= button_to edit_evaluation_form_path(evaluation_form), method: :get, class: "usa-button width-full", form: {class: "grid-col-6"} do %>
                  <%= image_tag(
                    "images/usa-icons/edit.svg",
                    class: "usa-icon icon-white",
                    alt: "evaluation forms"
                  )%>
                  Edit
                <% end %>
                <%= button_to evaluation_form, method: :delete, class: "usa-button usa-button--secondary width-full padding-x-1", form: {class: "grid-col-6"} do %>
                  <%= image_tag(
                    "images/usa-icons/delete.svg",
                    class: "usa-icon icon-white",
                    alt: "evaluation forms"
                  )%>
                  Delete
                <% end %>
              </div>  
          </td>  
        </tr>
      <% end %>  
    </tbody>
  </table>

app/views/evaluation_forms/edit.html.erb
<% content_for :title, "Editing evaluation form" %>

<h1><%= if eval_form_disabled?(@evaluation_form) then "View" else "Editing" end %> evaluation form</h1>

<%= render "form", evaluation_form: @evaluation_form %>

app/views/evaluation_forms/index.html.erb
<h1>Evaluation Forms</h1>
<p class="text-normal">Manage existing evaluation forms and create new evaluation forms.</p>

<p>
  <%= link_to new_evaluation_form_path, class: "width-full tablet:width-auto" do %>
    <button class="usa-button font-body-2xs text-no-wrap" style="background-color: #4d8055">
      <%= image_tag(
        "images/usa-icons/content_copy.svg",
        class: "usa-icon icon-white",
        alt: "evaluation forms"
      )%>
      Create New Evaluation Form
    </button>
  <% end %>
</p>

<% if @evaluation_forms.empty? %>
  <div class="text-normal">
    <p>You currently do not have any evaluation forms.<br/>
    Please create an evaluation form for your challenge before it is published.</p>
  </div>
<% else %>
  <%= render partial: "table", locals: { evaluation_forms: @evaluation_forms } %>
<% end %>  

app/views/evaluation_forms/new.html.erb
<% content_for :title, "Create Evaluation Form" %>

<h1>Create Evaluation Form</h1>

<%= render "form", evaluation_form: @evaluation_form %>

app/views/evaluation_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluation_form %>

<div>
  <%= link_to "Edit this evaluation form", edit_evaluation_form_path(@evaluation_form) %> |
  <%= link_to "Back to evaluation forms", evaluation_forms_path %>

  <%= button_to "Destroy this evaluation form", @evaluation_form, method: :delete %>
</div>