config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'auth/result', to: 'sessions#result'
  resource 'session', only: [:new, :create, :destroy]
  post 'sessions/renew', to: 'sessions#renew'
  delete 'sessions/timeout', to: 'sessions#timeout'

  get '/', to: "dashboard#index"
  get '/dashboard', to: "dashboard#index"

  resources :evaluations, only: [:index]
  resources :evaluation_forms
  resources :manage_submissions, only: [:index]

  namespace :form_validations do
    resources :evaluation_forms, only: %i[create update]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  if Rails.env.development? || Rails.env.dev?
    get "/sandbox", to: "sandbox#index"
  end
end

app/views/layouts/_footer.html.erb
<footer class="usa-footer usa-footer--big">
  <div class="usa-footer__primary-section">
    <div class="grid-container">
      <div class="usa-footer__return-to-top">
        <a href="#">Return to top</a>
      </div>
      <nav class="usa-footer__nav" aria-label="Footer navigation,,">
        <div class="grid-row grid-gap-4 usa-footer__primary-content padding-top-2 mobile-lg:padding-top-0 usa-footer__primary-content--collapsible">
          <div class="grid-col-5 mobile-lg:grid-col-6 desktop:grid-col-3">
              <%# Col 1 %>
              <ul class="usa-list usa-list--unstyled">
                <li class="usa-footer__secondary-link">
                  <a href="/about">About</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="/contact">Contact</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="/terms">Terms of use</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="/privacy-policy">Privacy Policy</a>
                </li>
              </ul>
          </div>
          <div class="grid-col-5 display-block desktop:display-none mobile-lg:grid-col-6">
          </div>
          <div class="grid-col-5 mobile-lg:grid-col-6 desktop:grid-col-3">
              <%# Col 2 %>
              <ul class="usa-list usa-list--unstyled">
                <li class="usa-footer__secondary-link">
                  <a href="/resources">Innovator Resources</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="/resources-managers">Agency Resources</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="/?state=archived">Archived Challenges</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="/#active-challenges">Active Challenges</a>
                </li>
              </ul>
          </div>
          <div class="grid-col-5 mobile-lg:grid-col-6 desktop:grid-col-3">
              <%# Col 3 %>
              <ul class="usa-list usa-list--unstyled">
                <li class="usa-footer__secondary-link">
                  <a href="https://www.gsa.gov/website-information/website-policies#privacy">GSA Privacy Policy</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="https://www.gsa.gov/website-information/accessibility-aids">Accessibility</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="https://www.gsa.gov/reference/freedom-of-information-act-foia">FOIA</a>
                </li>
                <li class="usa-footer__secondary-link">
                  <a href="https://www.usa.gov/">USA.gov</a>
                </li>
              </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
  <div class="usa-footer__secondary-section bg-primary-darker footer-white">
    <div class="grid-container">
      <div class="grid-row">
        <div class="usa-footer__logo flex-no-wrap flex-justify-end tablet:flex-justify-start margin-y-1 mobile-lg:grid-gap-2 mobile-lg:grid-col-12 tablet:grid-col-6">
          <div class="order-1 tablet:order-2" style="display: flex; align-items: center;">
            <img class="usa-footer__logo-img" src="<%= image_path('challenge-logo-white-orange.svg') %>" title="Challenge Gov wordmark" alt="Challenge Gov wordmark in footer" style="width: 220px; height: auto;" />
          </div>
          <div class="order-2 tablet:order-1">
            <img class="usa-footer__logo-img" src="<%= image_path('challenge-logo-square-white.svg') %>" title="GSA Star Mark" alt="GSA Star Mark" style="width: 60px; height: auto;" />
          </div>
        </div>
        <div class="usa-footer__contact-links mobile-lg:grid-col-12 tablet:grid-col-6 margin-y-1 footer-white">
          <div class="usa-footer__social-links flex-justify-end grid-row grid-gap-1">
            <div class="grid-col-auto">
              <a class="usa-social-link" href="https://www.twitter.com/ChallengeGov">
                <%= image_tag('images/usa-icons/twitter.svg', class: "usa-social-link__icon", alt: "Twitter") %>
              </a>
            </div>
            <div class="grid-col-auto">
              <a class="usa-social-link" href="https://www.facebook.com/ChallengeGov">
                <%= image_tag('images/usa-icons/facebook.svg', class: "usa-social-link__icon", alt: "Facebook") %>
              </a>
            </div>
            <div class="grid-col-auto">
              <a class="usa-social-link" href="https://www.youtube.com/@challenge-gov">
                <%= image_tag('images/usa-icons/youtube.svg', class: "usa-social-link__icon", alt: "YouTube") %>
              </a>
            </div>
            <div class="grid-col-auto">
              <a class="usa-social-link" href="https://www.linkedin.com/company/challengegov/">
                <%= image_tag('images/usa-icons/linkedin.svg', class: "usa-social-link__icon", alt: "LinkedIn") %>
              </a>
            </div>
            <div class="grid-col-auto">
              <a class="usa-social-link" href="https://github.com/GSA/Challenge_gov">
                <%= image_tag('images/usa-icons/github.svg', class: "usa-social-link__icon", alt: "Github") %>
              </a>
            </div>
          </div>
          <div class="grid-row flex-column text-right">
            <p class="usa-footer__contact-heading">
              Contact Us
            </p>
            <address class="usa-footer__address">
              <div class="usa-footer__contact-info">
                <div class="text-white">
                  <a style="color:white" href="mailto:team@challenge.gov">team@challenge.gov</a>
                </div>
              </div>
            </address>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section
class="usa-banner"
aria-label="Official website of the United States government"
>
  <div class="usa-accordion">
    <header class="usa-banner__header">
      <div class="usa-banner__inner">
        <div class="grid-col-auto">
          <img
            aria-hidden="true"
            class="usa-banner__header-flag"
            src="<%= image_path('images/us_flag_small.png') %>"
            alt=""
          />
        </div>
        <div class="grid-col-fill tablet:grid-col-auto" aria-hidden="true">
          <p class="usa-banner__header-text">
            An official website of the United States government
          </p>
          <p class="usa-banner__header-action">Here’s how you know</p>
        </div>
        <button
          type="button"
          class="usa-accordion__button usa-banner__button"
          aria-expanded="false"
          aria-controls="gov-banner-default"
        >
          <span class="usa-banner__button-text">Here’s how you know</span>
        </button>
      </div>
    </header>
    <div
      class="usa-banner__content usa-accordion__content"
      id="gov-banner-default"
    >
      <div class="grid-row grid-gap-lg">
        <div class="usa-banner__guidance tablet:grid-col-6">
          <img
            class="usa-banner__icon usa-media-block__img"
            src="<%= image_path('images/icon-dot-gov.svg') %>"
            role="img"
            alt=""
            aria-hidden="true"
          />
          <div class="usa-media-block__body">
            <p>
              <strong>Official websites use .gov</strong><br />A
              <strong>.gov</strong> website belongs to an official government
              organization in the United States.
            </p>
          </div>
        </div>
        <div class="usa-banner__guidance tablet:grid-col-6">
          <img
            class="usa-banner__icon usa-media-block__img"
            src="<%= image_path('images/icon-https.svg') %>"
            role="img"
            alt=""
            aria-hidden="true"
          />
          <div class="usa-media-block__body">
            <p>
              <strong>Secure .gov websites use HTTPS</strong><br />A
              <strong>lock</strong> (
              <span class="icon-lock"
                ><svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="52"
                  height="64"
                  viewBox="0 0 52 64"
                  class="usa-banner__lock-image"
                  role="img"
                  aria-labelledby="banner-lock-description-default"
                  focusable="false"
                >
                  <title id="banner-lock-title-default">Lock</title>
                  <desc id="banner-lock-description-default">Locked padlock icon</desc>
                  <path
                    fill="#000000"
                    fill-rule="evenodd"
                    d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z"
                  />
                </svg> </span
              >) or <strong>https://</strong> means you’ve safely connected to
              the .gov website. Share sensitive information only on official,
              secure websites.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="usa-overlay"></div>
</section> 
<header class="usa-header usa-header--basic site-header">
  <div class="desktop:display-flex desktop:width-full">
    <div class="usa-navbar">
      <div class="usa-logo">
        <em class="usa-logo__text"
          ><a href="/" title="challenge.gov">
          <span class="site-title--long">
            <img width="300" class="usa-header__logo-img desktop:margin-bottom-2" src="<%= image_path("challenge-logo.svg") %>" alt="challenge logo" />
          </span>  
          </a></em
        >
      </div>
      <button type="button" class="usa-menu-btn">Menu</button>
    </div>
    <nav aria-label="Primary navigation" class="usa-nav">
      <button type="button" class="usa-nav__close">
        <img src="<%= image_path('images/usa-icons/close.svg') %>" role="img" alt="Close" />
      </button>
      <ul class="usa-nav__primary usa-accordion flex-align-start">
        <li class="usa-nav__primary-item">
          <a href="/#active-challenges" class="usa-nav-link text-no-wrap"
            ><span>Find a Challenge</span></a
          >
        </li>
        <li class="usa-nav__primary-item">
          <a href="/resources" class="usa-nav-link"
            ><span>Resources</span></a
          >
        </li>
        <li class="usa-nav__primary-item">
          <a href="/events" class="usa-nav-link"
            ><span>Events</span></a
          >
        </li>
        <li class="usa-nav__primary-item">
          <a href="/contact" class="usa-nav-link"
            ><span>Contact</span></a
          >
        </li>
      </ul>
      <!-- Desktop search and login area --> 
      <section class="display-none desktop:display-flex">
        <section aria-label="Search component">
          <form class="usa-search usa-search--small" role="search">
            <label class="usa-sr-only" for="search-field-desktop">Search</label>
            <input
              class="usa-input"
              id="search-field-desktop"
              type="search"
              name="search"
              style="width: 140px"
            />
            <button class="usa-button" type="submit">
              <img
                src="<%= image_path('images/usa-icons-bg/search--white.svg') %>"
                class="usa-search__submit-icon"
                alt="Search"
              />
            </button>
          </form>
        </section>
        <% if logged_in? %>
          <%= button_to("Logout", session_path, method: :delete, class: "usa-button font-body-3xs usa-button--outline text-no-wrap desktop:margin-left-1", type: "button") %>
          <button class="usa-button font-body-2xs text-no-wrap">Switch Task</button> 
        <% else %>
          <%= button_to("Login", new_session_path, method: :get, class: "usa-button font-body-3xs usa-button--outline text-no-wrap desktop:margin-left-1", type: "button") %>
          <button class="usa-button font-body-2xs text-no-wrap">Create Account</button> 
        <% end %>
      </section>
      <!-- mobile search and login area --> 
      <section class="desktop:display-none order-3">
        <section aria-label="Search component">
          <form class="usa-search usa-search--small margin-y-1" role="search">
            <label class="usa-sr-only" for="search-field">Search</label>
            <input
              class="usa-input"
              id="search-field"
              type="search"
              name="search"
              style="width: 170px"
            />
            <button class="usa-button" type="submit">
              <img
                src="<%= image_path('images/usa-icons-bg/search--white.svg') %>"
                class="usa-search__submit-icon"
                alt="Search"
              />
            </button>
          </form>
        </section>
        <% if logged_in? %>
          <div class="text-primary font-body-2xs margin-y-1 padding-top-1">
            <%= current_user.email %>
          </div>  
          <%= button_to("Logout", session_path, method: :delete, class: "usa-button font-body-3xs usa-button--outline margin-y-1 text-no-wrap desktop:margin-left-1 width-full", type: "button") %>
          <button class="usa-button font-body-2xs text-no-wrap width-full margin-y-1">Switch Task</button> 
        <% else %>
          <%= button_to("Login", new_session_path, method: :get, class: "usa-button font-body-3xs usa-button--outline margin-y-1 text-no-wrap desktop:margin-left-1 width-full", type: "button") %>
          <button class="usa-button font-body-2xs text-no-wrap width-full margin-y-1">Create Account</button> 
        <% end %>
      </section>
    </nav>
  </div>
</header>

app/views/layouts/_utility_menu.erb
<!-- Utility Menu -->
<div class="bg-primary-darker w-full display-flex flex-justify-center desktop:flex-justify-end padding-1 font-body-3xs desktop:font-body-2xs text-white">
    <%= utility_menu_link('grid_view', dashboard_path, 'dashboard', 'Dashboard') %>
    <% if current_user.role == "challenge_manager" %>
      <%= utility_menu_link('emoji_events', Rails.configuration.phx_interop[:phx_uri], 'challenges', 'Challenges') %>
      <%= utility_menu_link('star_half', manage_submissions_path, 'Manage Submissions and Evaluations', 'Submissions & Evaluations') %>
      <%= utility_menu_link('check_circle_outline', evaluation_forms_path, 'Evaluation Forms', 'Evaluation Forms') %>
    <% end %>
    <% if current_user.role == "evaluator" %>
      <%= utility_menu_link('star_half', evaluations_path, 'Evaluate Submissions', 'Submissions & Evaluations') %>
    <% end %>  
    <%= utility_menu_link('support', 'https://www.challenge.gov/cm-user-guide/', 'Resources', 'Resources') %>
    <div class="display-none desktop:display-flex flex-align-center margin-x-1 margin-top-1">
      |
      <%= image_tag('images/usa-icons/account_circle.svg', class: "usa-icon--size-3 icon-white margin-x-2", alt: "Help") %>
      <%= current_user.email %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Challenge.gov</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "styles" %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <% if logged_in? %>
      <script>
        window.appConfig = {
          sessionTimeoutMinutes: <%= SessionsController::SESSION_TIMEOUT_IN_MINUTES %>
        }
      </script>

      <%= javascript_include_tag 'session_timeout' %>
    <% end %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if logged_in? %>
      <%= render "layouts/utility_menu" %>
    <% end %>  
    <%= render "shared/flash" %>

    <main class="grid-container">
      <%= yield %>
    </main>
    
    <%= render "layouts/footer" %>
    <%= render "modals/renew_session" %>
    <%= javascript_include_tag 'uswds', async: true %>
    <%= javascript_include_tag 'uswds-init', async: true %>
  </body>
</html>